[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# cargo bootimage
[build]
target = "x86_64-jos.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

# cargo build --target aarch64-jos.json
# cargo run --target aarch64-jos.json
[target.aarch64-unknown-none]
runner = "qemu-system-aarch64 -machine virt -cpu cortex-a57 -nographic -bios /usr/local/share/qemu/aarch64-efi-symlink.bin -kernel"

